### ISSUE TITLE
Compatibility with vanilla 2.5.2

### ISSUE THREAD

**Issue by ajjr1996** [ajjr1996/Witcher#1]

**Comment by rquinio** [comment]
Here's a list of things to check: http://www.ckiiwiki.com/Patch_2.5_mod_compatibility_guide

**Comment by ajjr1996** [comment]
Alright we can check some of those things out, I'm just kinda stumped. Anyway you can take a yonder?

**Comment by rquinio** [comment]
Apart from #5 , all points from http://www.ckiiwiki.com/Patch_2.5_mod_compatibility_guide are now handled !
