### ISSUE TITLE
Elves related issues

### ISSUE THREAD

**Issue by rquinio** [ajjr1996/Witcher#11]
I've noticed the following:
- ~~All elves tend to get the nickname 'the old' due to their longevity~~
- Elves children are using human child portraits
- ~~Create Hen Caerme decision is missing an icon~~
- d_gwendeith has placeholder flag

**Comment by ajjr1996** [comment]
I'm guessing we should figure out how to implement the elven child portraits from MEP into WK.

**Comment by rquinio** [comment]
I've opened separate issues #16 qnd #17 for the remaining, as it's not really a bug.
