### ISSUE TITLE
Missing trait icons

### ISSUE THREAD

**Issue by rquinio** [ajjr1996/Witcher#12]
Icons are missing for:
- ~~reasonable~~
- ~~solarist / imperialist (and associated decisions embrace_solarism / embrace_imperialism)~~
- ~~magic_talent~~
- ~~source~~
- ~~silver_tongued~~
- ~~mute~~
- ~~deaf~~

**Comment by rquinio** [comment]
@ajjr1996 What should be the background color for the solarist / imperialist traits ? Vanilla green for Mutazilite / Ashari might not fit.

**Comment by ajjr1996** [comment]
Purple? Idk.. You decide man. I trust you.

**Comment by rquinio** [comment]
Done !
