### ISSUE TITLE
Heroes pre-rendered portraits

### ISSUE THREAD

**Issue by rquinio** [ajjr1996/Witcher#27]
As it seems quite popular, I'll try to add them as optional.

To make it more flexible, better use:
- character ids as trigger rather than traits
- maybe an extra property layer

**Comment by rquinio** [comment]
There's a limitation to 26 frames in a sprite, so re-using the player_overlay (p11), does not allow to display all portraits.

An alternative would be to add 2 new layers (p14 and p15) to all ethnicities
It would also allow to fix the prison layer order (on top).
Drawback is that it means copying some vanilla / DLC .gfx definitions for the ethnicities used in the mod.

**Comment by ajjr1996** [comment]
These are mostly done except a few aren't popping up properly. Stennis and Henselt for example are still vanilla portraits.

**Comment by rquinio** [comment]
@ajjr1996 Did you try with 0.7.0 ? Stennis and Henselt should be fixed there.
