### ISSUE TITLE
Dynamic flags for Nilgaardian vassals

### ISSUE THREAD

**Issue by audiate** [ajjr1996/Witcher#32]
This idea was inspired by the e_iron_throne title's flag in the AGOT mod, which changes based on the ruling dynasty. I'm sure something similar can be done for vassals of empires.

Kingdom tier titles under empires (currently just Nilfgaard, but theoretically the North as well) could have flags that change depending on whether or not they're actively vassals of Nilfgaard. In other words, kingdoms like Nazair, Ebbing, Geso, Vicovaro, and so on, would have a different flag while vassals of Nilfgaard (the Nilfgaard sun, typically added above or next to the kingdom's original flag), but would revert back to their default, "de jure" flag while independent.

Here's a visual reference of what I mean, these flags being what the kingdom flags would look like while Nilgaardian vassals: http://i.imgur.com/8y0Fwgp.png

In AGOT, this works by events that resets the CoA of a title depending on who owns it, but it shouldn't be too difficult to reset it based on a liege's title, like e_nilfgaard, or the lack of one.

This can also be applied to places like Novigrad, with the CoA changing if Redania, for instance, controls it. There's already some flags online to use (after some editing) for that scenario, I think.

**Comment by rquinio** [comment]
Done !
