### ISSUE TITLE
Creation of 00_province_setup.txt

### ISSUE THREAD

**Issue by rquinio** [ajjr1996/Witcher#5]
common/province_setup/0_province_setup.txt file needs to be created with info from province history.
It's used when loading from a save.

**Comment by rquinio** [comment]
We should check if map filler tool can do this automatically.

**Comment by tannerflick4** [comment]
Hey rquinio - I could help you with this. I have done this file for many other mods such as lux invicta, zendar, and winter king - britannia.

**Comment by rquinio** [comment]
@tannerflick4 Thanks for proposing your help, I'm not very clear on the urgency of this issue, since it's quite some work, and because the missing file doesn't seem to have any impact ?! 
I've read somewhere this could impact the save loading time, as otherwise the game has to read province history files.

**Comment by tannerflick4** [comment]
Yeah I remember Lux invicta having trouble when people got farther into their saves. I can still do it for you, but maybe not with an urgency.

**Comment by rquinio** [comment]
Will close it for now, can be re-opened if save issues are spotted.
