### ISSUE TITLE
Magic system is no longer working

### ISSUE THREAD

**Issue by ajjr1996** [ajjr1996/Witcher#7]
The whole magic system is bugged and not working. Check out W_magic_events, all of those events are broken.

**Comment by rquinio** [comment]
The idea would be to define geographical regions for north / south, and use it to replace the e_the_north condition for some magic events by a region check.

**Comment by ajjr1996** [comment]
I added the geographical_regions.txt and divided it up to look orderly, we should later  add sub-realms as well instead of The North and The South. Idk we can do this later. For now I just want to implement what we have done.

**Comment by rquinio** [comment]
I've updated the triggers.
It's not easy to test because the magic talent system takes some time to kick in at game start (need new birth, then magic_talent event, etc... which take years, but I was able to add the trait magic_talent via console and use the decision to send to the academy.

**Comment by ajjr1996** [comment]
Thanks bro, and is it set up so if nilfgaard controls a northern province they will go to the nilfgaardian academy? and vice-versa?

**Comment by ajjr1996** [comment]
If a northerner controls a southern province have them go to the northern academies

**Comment by rquinio** [comment]
It's not done for the 2nd case and won't work with geographical regions.
Should it be based on culture groups instead ? Because a 'northerner' duke controlling a southern province, won't match geographical region world_the_north if his capital is in world_the_south !

**Comment by ajjr1996** [comment]
Do you know what I mean at least?

**Comment by rquinio** [comment]
This should be solved now
